# Generated by Django 4.2.5 on 2023-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
